"""empty message

Revision ID: 43357a9030cc
Revises: 558ee2013e68
Create Date: 2025-06-12 10:03:11.020648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43357a9030cc'
down_revision: Union[str, None] = '558ee2013e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_login_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    # ### end Alembic commands ###
