"""init

Revision ID: 5a01a825b098
Revises: 
Create Date: 2025-05-16 21:02:55.112713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a01a825b098'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('join_date', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'is_super_user')
    op.drop_column('users', 'join_data')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('join_data', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_super_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'join_date')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
