"""empty message

Revision ID: b993bc00801c
Revises: a17180f6b8e2
Create Date: 2025-06-23 11:22:26.257677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b993bc00801c'
down_revision: Union[str, None] = 'a17180f6b8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'room_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'room_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
