"""empty message

Revision ID: dc81394d60fc
Revises: 27e73d39970e
Create Date: 2025-07-17 11:30:18.194694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc81394d60fc'
down_revision: Union[str, None] = '27e73d39970e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_enabled')
    op.drop_column('users', 'otp_secret')
    # ### end Alembic commands ###
